### ISSUE TITLE
barge creates  ~/.ocean/ owned by root

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/barge#100]
## Expected Behavior

Typically in running a command one might expect that file system mutations
will be constrained to the current working directory -or- configurable
via some other means (environment variable, command line argument and/or
configuration file).

## Current Behavior

When running barge creates the directory `~/.ocean/` which, while surprising, isn't inherently a problem.

However that the directory is created owned by root is untenable: one of the barge components (via docker?) is using priviledge escalation to cause this file system mutation that only the superuser can counteract.

## Step to Reproduce the problem

1. On a new system verify that  `~/.ocean/ ` does not exist
2. Run start_ocean.sh
3. Verify that  `~/.ocean/ ` exists and is owned by root

### Possible Solution

Identify the component creating the filesystem mutation and remedy it.

## Specifications

* Version: develop HEAD
* OS: Ubuntu 18.04 LTS

## Failure Logs

_NOTE:_ in this log start_ocean.sh resists redirection to a log file and MUST be foregrounded (or stall waiting on STDIN). For more on this see #95 

```
robot@krill:~/src/github/oceanprotocol/barge$ groups
docker adm dialout cdrom floppy sudo audio dip video plugdev lxd netdev robot
robot@krill:~/src/github/oceanprotocol/barge$ pwd
/home/robot/src/github/oceanprotocol/barge
robot@krill:~/src/github/oceanprotocol/barge$ git pull
Already up to date.
robot@krill:~/src/github/oceanprotocol/barge$ ls -ld ~/.ocean
ls: cannot access '/home/robot/.ocean': No such file or directory
robot@krill:~/src/github/oceanprotocol/barge$ KEEPER_VERSION=v0.5.3 ./start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node  2>&1 > start-ocean-$(date +%m%d).log &
[1] 9832
robot@krill:~/src/github/oceanprotocol/barge$ Creating network "ocean_backend" with driver "bridge"
Creating volume "ocean_secret-store" with default driver
Creating volume "ocean_keeper-node" with default driver
Pulling keeper-node (parity/parity:stable)...
Pulling keeper-contracts (oceanprotocol/keeper-contracts:v0.5.3)...
Pulling secret-store (oceanprotocol/parity-ethereum:acl_docker)...

robot@krill:~/src/github/oceanprotocol/barge$ fg
KEEPER_VERSION=v0.5.3 ./start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node 2>&1 > start-ocean-$(date +%m%d).log
Pulling mongodb (mongo:3.6)...
Pulling aquarius (oceanprotocol/aquarius:latest)...
Pulling secret-store-cors-proxy (nginx:alpine)...
Creating ocean_secret-store_1 ...
Creating ocean_secret-store-signing-node_1 ...
Creating ocean_keeper-node_1 ...
Creating ocean_mongodb_1 ...
Creating ocean_secret-store_1
Creating ocean_secret-store-signing-node_1
Creating ocean_keeper-node_1
Creating ocean_secret-store_1 ... done
Creating ocean_secret-store-cors-proxy_1 ...
Creating ocean_mongodb_1 ... done
Creating ocean_aquarius_1 ...
Creating ocean_keeper-node_1 ... done
Creating ocean_keeper-contracts_1 ...
Creating ocean_keeper-contracts_1 ... done

^Z
[1]+  Stopped                 KEEPER_VERSION=v0.5.3 ./start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node 2>&1 > start-ocean-$(date +%m%d).log
robot@krill:~/src/github/oceanprotocol/barge$ bg
[1]+ KEEPER_VERSION=v0.5.3 ./start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node 2>&1 > start-ocean-$(date +%m%d).log &
robot@krill:~/src/github/oceanprotocol/barge$ ls -ld ~/.ocean
drwxr-xr-x 3 root root 4096 Jan 17 04:14 /home/robot/.ocean
robot@krill:~/src/github/oceanprotocol/barge$ 
```

**Comment by jcortejoso** [comment]
Hi @tmarble. Yeah, it is a bug related to how Docker manage permissions in Linux. It has been commented on #98. I will submit a PR soon with a fix.

**Comment by tmarble** [comment]
Unfortunately the fix to #98 does not address the root cause of this issue.

**Comment by H34D** [comment]
can this be closed?

**Comment by kremalicious** [comment]
eliminating root cause seems to be not feasible, so workaround should suffice for now
