### ISSUE TITLE
I want to register and purchase an asset in squid-py using barge running all of the services except plueston

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/barge#101]
## Expected Behavior

Purchase an asset via squid-py. With the full ocean stack running on ```barge``` ( except Plueston )

## Current Behavior

The asset DID is registered with the URL is to a local url  Aquarius in ```barge``` ( http:localhost:5000), so when Brizo resolves the DID, it gets the local address of Aquarius not the docker address for Aquarius ( http://aquarius:5000)

## Step to Reproduce the problem
```python
   service = ddo.get_service(service_type=ServiceTypes.ASSET_ACCESS)
            assert ServiceAgreement.SERVICE_DEFINITION_ID in service.as_dictionary()
            sa = ServiceAgreement.from_service_dict(service.as_dictionary())
            service_agreement_id = self._ocean.squid.purchase_asset_service(asset.did, sa.sa_definition_id, account)
            
            assert service_agreement_id, 'agreement id is None.'
            print('got new service agreement id:', service_agree
Please provide detailed steps for reproducing the issue.
```

1. Startup barge: 
`./start_ocean.sh --latest --no-pleuston --local-spree-node`
1. Unlock the account
1. Assign funds to the account
1. Register an asset
1. Try to buy the asset

### Possible Solution

Change the DID->URL  to resolve to http://aquarius:5000 
or 
Allow  have brizo/container to redirect http://localhost:5000 to http://aquarius:5000.

## Failure Logs
The brizo container logs in the ```barge``` container...

> brizo_1                      | 2019-01-17 08:24:36 1ba591619154 brizo[55] INFO got initialize request: {'did': 'did:op:95443d89cc4849deab294a3db8ea1b5828e553270a14442180ba581824fcbeb3', 'serviceAgreementId': '0xa2e01b4cb4b54aba9e233701b95b2de1d097ceca714540de8570bd3f6810fafa', 'serviceDefinitionId': '0', 'signature': '0x374aeb936c8b89a30f2b2f34255822ed34b7cfe7196a1ee8562a365fb46cd92b5e4479c3177dfe177542f033671697d79c0ea1eee41574aba6e64eaf622388c71c', 'consumerAddress': '0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e'}
> brizo_1                      | 2019-01-17 08:24:36,392 - keeper - DEBUG - got blockNumber 990 for did 0x95443d89cc4849deab294a3db8ea1b5828e553270a14442180ba581824fcbeb3
> brizo_1                      | 2019-01-17 08:24:36,399 - keeper - DEBUG - topics [HexBytes('0xfe303194f69c404a4ca19ca3d613a4bbcf419c764a463a930dd5686b5a6ba0f4'), HexBytes('0x95443d89cc4849deab294a3db8ea1b5828e553270a14442180ba581824fcbeb3'), HexBytes('0x00000000000000000000000000bd138abd70e2f00903268f3db08f2d25677c9e'), HexBytes('0x1f4f2b979ea7c19412f63673528a985ee418cd6d79ff2436472b43f96705a2e0')]
> brizo_1                      | 2019-01-17 08:24:36,399 - keeper - DEBUG - found did 0x95443d89cc4849deab294a3db8ea1b5828e553270a14442180ba581824fcbeb3 -> b'http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:95443d89cc4849deab294a3db8ea1b5828e553270a14442180ba581824fcbeb3'
> brizo_1                      | 2019-01-17 08:24:36 1ba591619154 brizo[55] ERROR HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/v1/aquarius/assets/ddo/did:op:95443d89cc4849deab294a3db8ea1b5828e553270a14442180ba581824fcbeb3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7138ced240>: Failed to establish a new connection: [Errno 111] Connection refused',))
> brizo_1                      | Traceback (most recent call last):
> brizo_1                      |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
> brizo_1                      |     (self._dns_host, self.port), self.timeout, **extra_kw)
> brizo_1                      |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
> brizo_1                      |     raise err
> brizo_1                      |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
> brizo_1                      |     sock.connect(sa)
> brizo_1                      | ConnectionRefusedError: [Errno 111] Connection refused
> brizo_1                      | 
> brizo_1                      | During handling of the above exception, another exception occurred:
> brizo_1                      | 
> brizo_1                      | Traceback (most recent call last):
> brizo_1                      |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
> brizo_1                      |     chunked=chunked)
> brizo_1                      |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
> brizo_1                      |     conn.request(method, url, **httplib_request_kw)
> brizo_1                      |   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
> brizo_1                      |     self._send_request(method, url, body, headers, encode_chunked)
> brizo_1                      |   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
> brizo_1                      |     self.endheaders(body, encode_chunked=encode_chunked)
> brizo_1                      |   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
> brizo_1                      |     self._send_output(message_body, encode_chunked=encode_chunked)
> brizo_1                      |   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
> brizo_1                      |     self.send(msg)
> brizo_1                      |   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
> brizo_1                      |     self.connect()
> brizo_1                      |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
> brizo_1                      |     conn = self._new_conn()
> brizo_1                      |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
> brizo_1                      |     self, "Failed to establish a new connection: %s" % e)
> brizo_1                      | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7138ced240>: Failed to establish a new connection: [Errno 111] Connection refused
>

**Comment by jcortejoso** [comment]
Hi Bill! Thanks for reporting. 
We were thinking about this problem some time ago and we did not find a clever solution. Maybe thinking about redirecting traffic in brizo container (with `socat` for example) can be a workaround at the moment, but also is a very specific workaround (and would need to add logic in brizo container that only apply in `barge` environment).

**Comment by eruizgar91** [comment]
Hi @billbsing 
We are not able to reproduce this. If you can take a look in the examples folder in squid-py there is one called `buy_asset` and it is showing an example of how to buy and asset using squid-py.
Can you take a look and if the error continue give us more information to try to reproduce it.
Thank you

**Comment by billbsing** [comment]
I know, it's all changed since I did this issue. 
Currently I'm using BrizoMock to do testing, instead of using barge. Lets close this one & I'll re-open it if it's still an issue.
