### ISSUE TITLE
./start_ocean.sh fails because there's no "stable" brizo image in Docker Hub

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/barge#104]
This issue was reported by an external party.

The default recommended command to start the ocean in the readme:

```text
git clone git@github.com:oceanprotocol/barge.git
cd barge
./start_ocean.sh
```

fails with the following error:

**ERROR: manifest for oceanprotocol/brizo:stable not found**

due to the fact that there’s no brizo Docker image labelled **stable** available in the Docker image
registry.

The readme claims this would bring up stable versions of all components, but brizo doesn’t have a
**stable** image yet.

**Comment by H34D** [comment]
https://github.com/oceanprotocol/brizo/issues/25

**Comment by ttmc** [comment]
I will close this issue as a duplicate.
