### ISSUE TITLE
Upgrade from Docker Compose 2.1 to 3

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/barge#105]
This issue was reported by an external party.

It's a nice-to-have, not critical for Tethys.

Individual docker-compose files follow a standard pattern with Compose File version 2.1. Although it’s
serving the purpose of the repositories today, to be future-proof and also to set a modern example to
future integrators, docker-compose files could be upgraded to version 3. Version 3 and up bring many
new features to docker-compose, making it a native part of Docker stack including Swarm. This would
allow for a seamless integration into modern Swarm stacks.

**Comment by jcortejoso** [comment]
Hi! 
I have updated the compose files to version 3 and seems to work. I have pushed to https://github.com/oceanprotocol/barge/tree/feature/compose_3. I will try to verify with the CI tests that everything works.

**Comment by ttmc** [comment]
Resolved by pull request #118
