### ISSUE TITLE
Aquarius crashes on startup on stable

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/barge#113]
## Expected Behavior
Aquarius to start up in barge with no errors.

## Current Behavior

Aquarius crashes on startup in the lastest barge.
I have successfully started up a standalone version of aquarius from the aquarius repo, with a docker mongo db container. 

Hence this issue is being raised here.

## Step to Reproduce the problem

Start barge using the following commands:
```bash
# first delete all docker images/containers/volumes - full nuke!
./cleanDocker.sh 
# go to the barge repo
cd barge
# make sure we have the latest
git checkout develop
git pull
# start ocean local test
./start_ocean.sh --no-brizo --no-pleuston --local-spree-node
```

## Failure Logs
>aquarius_1                   | [2019-02-13 02:25:08 +0000] [7] [INFO] Starting gunicorn 19.9.0
aquarius_1                   | [2019-02-13 02:25:08 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
aquarius_1                   | [2019-02-13 02:25:08 +0000] [7] [INFO] Using worker: sync
aquarius_1                   | [2019-02-13 02:25:08 +0000] [9] [INFO] Booting worker with pid: 9
aquarius_1                   | [2019-02-13 02:25:08 +0000] [9] [ERROR] Exception in worker process
aquarius_1                   | Traceback (most recent call last):
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
aquarius_1                   |     worker.init_process()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
aquarius_1                   |     self.load_wsgi()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
aquarius_1                   |     self.wsgi = self.app.wsgi()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
aquarius_1                   |     self.callable = self.load()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
aquarius_1                   |     return self.load_wsgiapp()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
aquarius_1                   |     return util.import_app(self.app_uri)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
aquarius_1                   |     __import__(module)
aquarius_1                   |   File "/provider/provider/run.py", line 27, in <module>
aquarius_1                   |     from provider.app.assets import assets
aquarius_1                   |   File "/provider/provider/app/assets.py", line 18, in <module>
aquarius_1                   |     dao = Dao(config_file)
aquarius_1                   |   File "/provider/provider/app/dao.py", line 7, in __init__
aquarius_1                   |     self.oceandb = OceanDb(config_file).plugin
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/oceandb.py", line 19, in __init__
aquarius_1                   |     self.plugin = start_plugin(file_path)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/utils.py", line 37, in start_plugin
aquarius_1                   |     plugin_instance = load_plugin(config)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/utils.py", line 65, in load_plugin
aquarius_1                   |     return mod.Plugin(config)
aquarius_1                   | TypeError: Can't instantiate abstract class Plugin with abstract methods text_query
aquarius_1                   | [2019-02-13 02:25:08 +0000] [9] [INFO] Worker exiting (pid: 9)
aquarius_1                   | [2019-02-13 02:25:08 +0000] [7] [INFO] Shutting down: Master
aquarius_1                   | [2019-02-13 02:25:08 +0000] [7] [INFO] Reason: Worker failed to boot.

**Comment by billbsing** [comment]
I forgot to add that pesky `--latest` option for `start_ocean.sh`. But I will leave this open, as this is still an issue for the stable docker builds.

**Comment by eruizgar91** [comment]
At the moment to integrate all the components you need to use --latest, we will be using this until we release all the components stable.

**Comment by kremalicious** [comment]
At the time of writing, running `start_ocean.sh` successfully brings up Aquarius, so closing this
