### ISSUE TITLE
No acl contract address found when using keeper version 0.6.12 or a version not in the list

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/barge#124]
## Expected Behavior

No acl contract address found if the keeper version is set to a version that is not found in the follwing files:

+ nile_acl_contract_addresses.txt
+ kovan_acl_contract_addresses.txt

## Step to Reproduce the problem

1. export KEEPER_VERSION=0.6.12
2. ./start_ocean.sh --no-pleuston --local-nile-node --latest
3.

### Possible Solution

Possible soultions:

1. Addd then line
> v0.6.12=0x6bd5fdc37b9c87ba73dda230e5dc18e9fda71ff9

2. if the version is not found used the _latest_ version

3. **Exit from start_ocean with an error**.

The only reason I found this is the config.toml file contained the following setting for acl contract:

```
acl_contract = "nnot determine the ACL Contract Address for nile version v0.6.12. Exiting"
```

## Failure Logs

> secret-store_1               | ACL Contract Address: Cannot determine the ACL Contract Address for nile version v0.6.12. Exiting
> secret-store_1               | Loading config file from /etc/parity/secretstore/config.toml
> secret-store_1               | Invalid character 'n' at position 0
> ocean_secret-store_1 exited with code 1
>

**Comment by H34D** [comment]
we do not run local secret stores for networks already having secret stores, like `nile`, `duero`, `kovan` or `pacific`

**Comment by billbsing** [comment]
It was to do with getting the contract address in Barge. I originally added this issue because the address for this version of keeper was not in the files.

+ nile_acl_contract_addresses.txt
+ kovan_acl_contract_addresses.txt

This has now been fixed..

**Comment by kremalicious** [comment]
great! Thanks for reporting back
