### ISSUE TITLE
The artifacts folder is missing or contains incorrect contract versions/address when running network nodes Nile or Kovan

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/barge#125]
This an interesting one ...

The folder `.ocean/keeper-contracts/artifacts` is a shared volume for all of the docker containers to share the keeper artifacts within docker.

The contents of this artifacts folder is only populated by the `--local-spree-node` or by the `--local-ganache-node` options. 

When barge starts with a local test node, the artifact files are only populated for the requested keeper version.

You can create errors by doing the following:

1. Brizo will not have any artifact files & pleuston will run the default artifact files saved for squid-js:
    a. remove ~/.ocean folder
    b. Start barge with `--local-nile-node` or `--local-kovan-node`.

2. Brizo & pleuston will have have keeper 0.5.3 version of the artifact files, whilst the barge node runs on keeper v0.6.12:
    a. Set keeper_version to 0.5.3
    b. Start barge  with`--local-spree-node` or `--local-ganache-node`
    c. Stop barge
    d. Set keeper_version to 0.6.12
    e. Start barge with `--local-nile-node` or `--local-kovan-node`.

**Comment by ssallam** [comment]
I think for both of these the user can simply try not to remove the folder in 1., and in 2. it is recommended to reset the local keeper node (remove the parity container and image) when switching between different network such as between `spree` and `nile`.
