### ISSUE TITLE
config.toml is mutated when running barge

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/barge#126]
## Expected Behavior

Running barge should not cause barge git artifacts to change.

## Current Behavior

Simply running barge causes a mutation to the file [config.toml](https://github.com/oceanprotocol/barge/blob/develop/networks/secret-store/config/config.toml) requiring users to revert it to update git or change branches.

## Step to Reproduce the problem

1. run barge
2. enter `git status` and see
```
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   networks/secret-store/config/config.toml

no changes added to commit (use "git add" and/or "git commit -a")
```

### Possible Solution

1. Add `networks/secret-store/config/config.toml` to `.gitignore`
2. Check in a "template" version of the file under a different path, say `networks/secret-store/config/config.toml.saved`
3. Have `start_ocean.sh` copy `config.toml.saved` to `config.toml` on startup

## Specifications

* Version: `530f0d56cac3334ccb46e4fdaa9a3f661bd6cb1f`
* Python: `Python 3.7.2+`
* Solidity: 
* JavaScript: 
* Node: `v10.14.2`
* OS: `Linux cerise 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux`

**Comment by ttmc** [comment]
I was able to reproduce (just now) using:

`./start_ocean.sh --local-spree-node`

(which default to `stable` for Aquarius, Brizo, Keeper and Pleuston today) but not using:

`./start_ocean.sh --local-spree-node --latest`

**Comment by jcortejoso** [comment]
Hi! Effectively the secret store node/container will modify its config file because the acl_contract address is different for each deployment/version/network, and it is calculated on execution.

@tmarble I think your approach is the best one I can think of. If you want to submit a PR with the improvement the are welcomed.

Thanks!
