### ISSUE TITLE
Barge needs a hard-pin --stable=x.y.z option

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/barge#127]
## Expected Behavior

It should be possible for any user to reproduce precise barge behavior (as demonstrated by running hard-pinned versions of _every_ component service).

## Current Behavior

The current behavior specifies docker containers with the label `:latest`, but docker container labels are _reused_ on dockerhub meaning that _every time_ barge is invoked the actual services presented will vary depending on whatever has been updated to dockerhub.

Even the proposed PR #119 to add a `--stable` flag does not go far enough because the reuse of the `stable` docker tag leads to the same problem.

## Step to Reproduce the problem

1. run barge with specific command line arguments
2.  enter: `docker images --digests`
3. run barge again (as in step 1) a few hours or a day later with the exact same command line arguments
4. enter: `docker images --digests`
5. Notice the SHA256 checksums for the docker containers have changed!

### Possible Solution

Due to the lack of dockerhub community discipline around non-immutabiliy of tags the way to precisely identify container versions is to use the SHA256 checksum.

An example can be seen in the DEX fork of barge where the version number of each service explicitly starts either with a colon and a tag or `@sha256:` and a [digest](https://github.com/DEX-Company/barge/blob/develop/start_ocean.sh#L21):
`export MONGO_VERSION=${MONGO_VERSION:-"@sha256:0b4646755d68c9a5f2283be540792cf2f11d85c5492a43fd6a65b8547b6749ca"}`

Note that a regular label may also be [used](
https://github.com/DEX-Company/barge/blob/develop/start_ocean.sh#L128):
`export MONGO_VERSION=":3.6"`

The docker compose files need to be updated by [removing the assumed colon](https://github.com/DEX-Company/barge/blob/develop/compose-files/aquarius.yml#L16)

Of course this allows users to specifiy any given component precisely by setting the corresponding env var to the intended label or digest.

By giving barge an overall version which specifies each component service precisely by SHA256 digest it will be possible to have reproducable behavior -- a critical need for testing Ocean components and for prospective Ocean developers. In other words specifying, for example,  `--stable=0.9.0` should imply specific **SHA256 digests for each component service**. It is critically important that the overall barge version be immutable: if any one component service changes the overall barge version _must_ change too.

FFI:
- https://hub.docker.com/r/oceanprotocol/aquarius/tags
- https://docs.docker.com/registry/spec/api/#/listing-image-tags
- https://hub.docker.com/v2/repositories/oceanprotocol/aquarius/tags/ 

## Specifications

* Version: `530f0d56cac3334ccb46e4fdaa9a3f661bd6cb1f`
* Python: `Python 3.7.2+`
* Solidity:
* JavaScript:
* Node: `v10.14.2`
* OS: `Linux cerise 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux`

**Comment by ttmc** [comment]
This is a nice idea. In fact, my pull request #119 started off proposing something similar (but not using hash digests) but it changed over time.

For now, I would recommend setting a bunch of environment variables before running `./start_ocean.sh` e.g.

```bash
export AQUARIUS_VERSION=v0.1.10
export BRIZO_VERSION=v0.2.2
export KEEPER_VERSION=v0.6.12
etc.
./start_ocean.sh --local-spree-node --no-pleuston
```

Note: I don't think there's currently an environment variable that can set the MongoDB version.

**Comment by aaitor** [comment]
This is the Tethys list of versions that can be specified configured for the stable version:

Layer       |   Component               |   Version     
------------|---------------------------|---------------
L1          | keeper-contracts          | 0.9.0         
L2          | squid-py                  | 0.5.11        
L2          | squid-js                  | 0.5.0         
L2          | squid-java                | 0.4.0         
L2          | brizo                     | 0.3.1         
L2          | aquarius                  | 0.2.0             
L3          | pleuston                  | 0.3.0
