### ISSUE TITLE
Change the default network from Nile to Spree

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/barge#128]
This idea came up at the sprint planning meeting yesterday.

Currently, the default network is Nile, but that's not a great user experience because it can take several minutes for the local Nile node to get in sync with the Nile network and meanwhile it's not very useful.

https://github.com/oceanprotocol/barge/blob/c5e2e1591c26e8f6400caa536e6cfb6d8a8bb398/start_ocean.sh#L27

**Proposal:** Change the default network to Spree (i.e. a local Parity-based network).

**Comment by jcortejoso** [comment]
Hi Troy! Thanks for the idea. What is your feeling about it @aaitor ?

**Comment by aaitor** [comment]
looks a good idea to me
