### ISSUE TITLE
Secret Store Client.js:235 has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/barge#130]
## Expected Behavior

The Secret Store server on Nile, does provide the header:
Access-Control-Allow-Origin

## Current Behavior

The secret store library cannot access the secret store server on the Nile test net, because the header returned from the secret store server does not allow 'Access-Control-Allow-Origin'

## Step to Reproduce the problem

1. Setup and run barge for the Nile network, and with pleuston. ( see versions below )
2. Open the web browser console.
3. Purchase an asset in _pleuston_.

### Possible Solution

Run the web browser with a 'CORS Eveyrwhere' plugin, not sure if this will work since the request is being made from _SecretStoreClient.js:235_

## Specifications

keeper: 0.5.3
brizo:  0.1.7
aquarius: 0.1.5
pleuston: latest

## Failure Logs
Errors reported from the browser console...

SecretStoreClient.js:235 GET https://secret-store.dev-ocean.com/shadow/9670f80ca3e1426da91984ffc5dfdd181de1e9c9520d476dbf413895b4329752/4886c27c2ac17edd17fbadeac75dcbeb7e00dc96a9f3d08c449b0cf3f526d08613169f18333cd75ac8823684fa4b097e7a952ab48af96d10fba7d0a7096568eb00 403 (Forbidden)

:3000/did:op:9670f80ca3e1426da91984ffc5dfdd181de1e9c9520d476dbf413895b4329752:1 Access to fetch at 'https://secret-store.dev-ocean.com/shadow/9670f80ca3e1426da91984ffc5dfdd181de1e9c9520d476dbf413895b4329752/4886c27c2ac17edd17fbadeac75dcbeb7e00dc96a9f3d08c449b0cf3f526d08613169f18333cd75ac8823684fa4b097e7a952ab48af96d10fba7d0a7096568eb00' from origin 'http://health1a.ocean:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Uncaught (in promise) Error: Unable to retrieve decryption keys: Failed to fetch
    at SecretStoreClient.js:250

**Comment by jcortejoso** [comment]
Hi @billbsing. Sorry not answiring before but the issue was fixed some weeks ago.
Thanks!
