### ISSUE TITLE
ocean protocol barge No accounts found :-( Have you checked your Keeper connection?

### ISSUE THREAD

**Issue by pblin** [oceanprotocol/barge#138]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository.

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior
run ./start_ocean.sh --latest
open http://localhost:3000

message: 
ocean protocol barge No accounts found :-( Have you checked your Keeper connection?

evnt keeper container is running. 

What is the current behavior? Please provide as many details as possible.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1.
2.
3.

### Possible Solution

Fill this section in if you know how this could or should be fixed.

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: x.x.x
* Python: x.x
* Solidity: x.x.x
* JavaScript: x.x.x
* Node: x.x.x
* OS: macOS/linux/win

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by jcortejoso** [comment]
Hi @pblin. Sorry about the delay replying. I cannot reproduce the issue. Can you provide the logs of the containers? Also feel free in reach us at gitter https://gitter.im/oceanprotocol/Lobby.

**Comment by kremalicious** [comment]
Not reproducable, please reopen if problem still persists
