### ISSUE TITLE
consuming fails, requested did is not found in the keeper network

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#144]
Upon running through our React app tutorial, which is a very minimal test case for using barge & squid-js, we run into an issue during the consume flow.

With all the changes in https://github.com/oceanprotocol/docs/pull/216, when starting barge with this:

```bash
export KEEPER_VERSION=v0.9.1 && \
export AQUARIUS_VERSION=v0.2.2 && \
export BRIZO_VERSION=v0.3.5 && \
./start_ocean.sh --no-pleuston
```

Consuming an asset returns, e.g.:

```
Error requesting [POST] http://localhost:8030/api/v1/brizo/services/access/initialize 
Response message: 
Requested did is not found in the keeper network: DID "0xdd3743f4be364ad58359dc2365e67a85bdb96318482c4c23ba86f370d3946c3f" is not found on-chain in the current did registry. Please ensure assets are registered in the correct keeper contracts. The keeper-contracts DIDRegistry address is 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e
```

So some contracts seem to be different somewhere.

I put this issue here cause it's not clear where and in what component exactly the problem is. Might be a Brizo problem, might be some contract mismatches between keeper contracts and squid-js.

### Reproduce

1. from the tutorial do the initial steps "Requirements" & "New Create React App" in https://docs.oceanprotocol.com/tutorials/react-setup/
2. create a `src/asset.js` file and fill with content from https://docs.oceanprotocol.com/tutorials/react-publish-data-set/#define-asset
3. replace your `src/App.js` with the contents of the final result of last step in https://docs.oceanprotocol.com/tutorials/react-get-use-data-set/#final-result
4. run `npm start`, under localhost:3000 register & retrieve and asset. Then hit consume button, look into console.log to see the errors

**Comment by jcortejoso** [comment]
Hi @kremalicious, does https://github.com/oceanprotocol/squid-js/pull/209 solved the issue?
