### ISSUE TITLE
Docker repo Parity:v2.3.2 not found

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/barge#147]
## Current Behavior

A new instance of barge starting on a fresh docker build. Fails with no docker repo found for parity v2.3.2

## Failure Information (for bugs)
```
Creating volume "ocean_keeper-node" with default driver
Creating volume "ocean_secret-store" with default driver
Pulling keeper-node (parity/parity:v2.3.2)...
ERROR: manifest for parity/parity:v2.3.2 not found
```
This tag no longer exists in the docker repo for parity, see: https://hub.docker.com/r/parity/parity/tags

### Possible Solution

Edit `compose-files/nodes/nile_node.yml` and change the parity version to v2.3.3

**Comment by kremalicious** [comment]
Seems to work again, current version is `parity:v2.3.3` which successfully gets fetched
