### ISSUE TITLE
Feature request: Using remote nodes

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/barge#153]
Running the Ocean stack on your local machine can be painful when using `kovan` or `nile` with lots of new blocks and traffic.

Proposal:

Add 

- `--remote-nile-node`
- `--remote-kovan-node`

configuration flags that will switch the keepers node URL to `https://kovan.infura.io/v3/<token>` or `https://nile.dev-ocean.com`

**Comment by kremalicious** [comment]
whoops, wrong issue number in #166, re-opened

**Comment by ssallam** [comment]
This is now possible with the new squid-py and related libraries. The user would still have to run a local node but it does not need to be connected to the keeper network, it is only used for signing transactions for the secret-store operation. Squid-py supports two separate parity urls. One for the keeper node (keeper.url) and another for the secret-store-signing node (parity.url).

**Comment by H34D** [comment]
> This is now possible with the new squid-py and related libraries. The user would still have to run a local node but it does not need to be connected to the keeper network, it is only used for signing transactions for the secret-store operation. Squid-py supports two separate parity urls. One for the keeper node (keeper.url) and another for the secret-store-signing node (parity.url).

thanks for the info. Keep up the good work
