### ISSUE TITLE
Pleuston build fails sometimes, serves unfinished build

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#158]
Running `./start_ocean --latest` (with Pleuston `v0.4.0` as of right now). Docker for macOS `v2.0.0.3`

## Expected Behavior

Pleuston is built successfully and then served on localhost:3000

## Current Behavior

Build of Pleuston starts at the right time, but then after a while gets killed with nothing more than a `Killed` message:

```
pleuston_1                   | Waiting for contracts to be generated...
...
pleuston_1                   | 
pleuston_1                   | > @oceanprotocol/pleuston@0.4.0 build /pleuston
pleuston_1                   | > node --max_old_space_size=4096 scripts/build.js
pleuston_1                   | Copying keeper-contracts artifacts...
pleuston_1                   | 
pleuston_1                   | Successfully copied keeper-contracts artifacts.
pleuston_1                   | Creating an optimized production build...
...
pleuston_1                   | Killed
pleuston_1                   | INFO: Accepting connections at http://0.0.0.0:3000
```

This then will serve an incomplete build when accessing localhost:3000

### Possible Solution

This is most likely a memory issue, Docker for Mac limits memory to 2GB by default https://docs.docker.com/docker-for-mac/#advanced and it seems not enough to run the network, and build Pleuston and all its modules at the same time.

We might have to instruct users to increase that manually.

Stopping all Docker containers and running the script again usually makes it work as expected.

**Comment by H34D** [comment]
Maybe we don't need to increase it but shift it from the containers that don't need so much like aqua und brizo:

https://linuxhint.com/docker_compose_memory_limits/

**Comment by kremalicious** [comment]
Barge now runs the development server by default, greatly reducing the time and resources required to start up
