### ISSUE TITLE
Aquarius-Brizo communication in Spree

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#171]
When testing against Spree, in multiple frontend projects, there seems to be an issue which we thought is only happening on macOS (because of [known limitation of Docker for Mac](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds)) where we have to set a special hostname for Aquarius. Otherwise consuming in pleuston or commons just times out with no errors. But now it seems this is also required on Linux.

## Current Behavior

Hosts workaround seem to be required for all OS. E.g. when running barge and commons locally on macOS we have to do:

```bash
sudo vi /etc/hosts

# add this line, and save
127.0.0.1    aquarius
```

And then use `http://aquarius:5000` as the `REACT_APP_AQUARIUS_URI` before starting up commons. Now we see this also being required on Linux. E.g. for integration tests squid-js has to use internal Docker IP of Aquarius: https://github.com/oceanprotocol/squid-js/blob/master/integration/config.ts#L6

For commons/Spree integration tests on Travis we also modify the hosts file as above and this resulted in successful consuming: https://github.com/oceanprotocol/commons/pull/179/commits/b112f3aa600b1ea4e10d044318afe6dca197abd4

## Expected behavior

No `/etc/hosts` workaround should be required except on macOS if it turns out that this is a known limitation. On Linux that should not be a problem though and no hosts workarounds should be required for it.

**Comment by H34D** [comment]
related to: https://github.com/oceanprotocol/pleuston/pull/212
