### ISSUE TITLE
--force-pull option fails

### ISSUE THREAD

**Issue by theoturner** [oceanprotocol/barge#172]
## Expected Behavior

Adding the `--force-pull` option should force pull the images.

## Current Behavior

Docker returns `No such command`.

## Failure Information (for bugs)
```
./start_ocean.sh --force-pull
```
```
Pulling the latest revision of the used Docker images...

Starting Ocean...

No such command: 

Commands:
  [LIST OF AVAILABLE COMMANDS]
```

## Step to Reproduce the problem

```
./start_ocean.sh --force-pull
```

## Specifications

* Version: bf8a9f0
* OS: macOS

**Comment by H34D** [comment]
fixed with #173
