### ISSUE TITLE
Default Brizo & Faucet connection is broken

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#208]
When starting current `master` with `./start_ocean.sh` on macOS and at the end opening Commons, I end up with:

<img width="1390" alt="Screen Shot 2020-01-22 at 18 28 25" src="https://user-images.githubusercontent.com/90316/72917907-fecade80-3d44-11ea-878f-9cc28d7050bc.png">

That problem seem to have been introduced with https://github.com/oceanprotocol/barge/commit/e7748228700282f4d534616aaf47978a3f641afa where `http://brizo` just doesn't work on a user's system. For `http://aquarius` we specifically modify the user's `/etc/hosts` file but we don't do that for Brizo or Faucet, hence the connections fail in Commons

**Comment by kremalicious** [comment]
git blame @alexcos20 for e774822 :-) Think we have to revisit that `localhost` thing so Commons can work. Was there a reason for changing it to `http://brizo`?

**Comment by alexcos20** [comment]
Yes, it was for sure, but I cannot recall it now.  I will update you

**Comment by alexcos20** [comment]
The issue appears only on Mac, it seems it's working fine on Linux

**Comment by kremalicious** [comment]
fixed in https://github.com/oceanprotocol/barge/pull/207
