### ISSUE TITLE
Stalled when trying to install Barge, get "this might be a longer run"

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/barge#225]
## Expected Behavior

I want to install Barge on Ubuntu Linux for the very first time. I installed Docker Engine and Docker Compose and checked it. So far so good. When trying to get Barge from Git I receive an error.

## Current Behavior

When trying to install barge with "git clone git@github.com:oceanprotocol/barge.git" I receive a message indicating there might a problem with the keys/access

> Cloning into 'barge'...
> The authenticity of host 'github.com (140.82.121.4)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
> Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

> OS: Distributor ID:	Ubuntu
> Description:	Ubuntu 20.10
> Release:	20.10
> Codename:	groovy

I appreciate any help you could give running through the whole process as a complete newbie. Thanks a lot.

**Comment by kaimeinke** [comment]
Okay ...

> git clone https://github.com/oceanprotocol/barge.git

worked perfectly.

Was this an error in the documentation?

**Comment by kaimeinke** [comment]
Onto the next ... the Barge Installation did not run initially with 

> ./start_ocean.sh

This resulted in

> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
> See 'docker run --help'.

Running 

> sudo ./start_ocean.sh

did the trick for me.

These were expected ...

> Starting Ocean V3...
> 
> WARNING: The PROVIDER_ADDRESS variable is not set. Defaulting to a blank string.
> WARNING: The PROVIDER_PASSWORD variable is not set. Defaulting to a blank string.
> WARNING: The PROVIDER_ENCRYPTED_KEY variable is not set. Defaulting to a blank string.
> WARNING: The GANACHE_REUSE_DATABASE variable is not set. Defaulting to a blank string.

This might be alright as well ?

> Pulling ocean-contracts (oceanprotocol/ocean-contracts:v0.5.8)...
ERROR: manifest for oceanprotocol/ocean-contracts:v0.5.8 not found: manifest unknown: manifest unknown

**Comment by kaimeinke** [comment]
When looking at the default installation I see that the version of Aquarius appears to be outdated.

Aquarius v2.1.13 is now v2.2.2 
Provider v0.4.3 is the latest version
Ganache is the latest version
ocean-contracts v0.5.8 is the latest version

Is an Aquarius update recommended for a new Compute-to-Data setup @alexcos20 ?

**Comment by kaimeinke** [comment]
I took my chance and got me Aquarius v2.2.2.

> sudo docker system prune --all --volumes

> export AQUARIUS_VERSION=v2.2.2

> sudo ./start_ocean.sh

**Comment by kremalicious** [comment]
> When trying to install barge with "git clone git@github.com:oceanprotocol/barge.git" I receive a message indicating there might a problem with the keys/access

This is your GitHub setup, please decide and follow the steps to setup the authentication you prefer: https://docs.github.com/en/github/authenticating-to-github/about-authentication-to-github#authenticating-with-the-command-line

> Onto the next ... the Barge Installation did not run initially with ./start_ocean.sh

This is because of the default Docker Ubuntu setup, see https://stackoverflow.com/questions/51218233/docker-why-do-i-need-to-sudo-in-ubuntu

In general, this is not a support forum. If you have a specific issue please tell us, but I see that you seem to have solved the initial reported issue.

**Comment by kremalicious** [comment]
and also worth noting regarding Compute-to-Data: `barge` does not include the components required to run compute jobs which requires another set of components running in a Kubernetes cluster and we were never able to replicate this locally in Docker only. Hence the still rather complex instructions which might require some updates by now https://docs.oceanprotocol.com/tutorials/compute-to-data/

So if you find something not working as expected, it might make sense opening up an issue over on the docs then. We highly value improving our documentation right now so would be super valuable right now to get this double-checked

**Comment by kaimeinke** [comment]
Thanks a lot @kremalicious for the wonderful feedback. I will work my way through everything, just step by step, and I have some support from Frederic (Data Protection Officer for Data Union). I could also imagine this to be a full DAO proposal to create a full walkthrough for others to set up C2D environments in a straightforward way. This could help the market and Ocean Protocol a lot.

**Comment by jamiehewitt15** [comment]
It sounds like this issue is solved? I suggest we close this
