### ISSUE TITLE
add network explorer

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#236]
**Is your feature request related to a problem? Please describe.**
At the moment transactions happening within barge can only be inspected via scripts, or with externally running tools. When using the `market` to run against barge, it's often critical to see transactions by linking to some explorer.

**Describe the solution you'd like**
Find an open source explorer we can run as additional block in barge. This is then pointed against the local running ganache node & network.

**Describe alternatives you've considered**
We could give instructions on how to find transactions somehow in barge, or have instructions how to run an explorer outside of barge.

**Additional context**
With https://github.com/oceanprotocol/ocean.js/pull/643, a new `explorerUri` config item already exists. Once we arrive at https://github.com/oceanprotocol/market/issues/413 the question arises what to do with transactions links when using the `market` with barge.

**Comment by alexcos20** [comment]
@md00ux  - take a look at blockscout.  it should work out of the box

**Comment by md00ux** [comment]
`barge feature/blockscout` branch has Blockscout included.

**Comment by trentmc** [comment]
This issue is a "nice to have". It's two years old. Even though there's a solution, it seems not enough of a priority to bother to fix. So, closing.
