### ISSUE TITLE
Chain ID should be 1337 on v4 branch

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/barge#269]
Recent commit added `"--chainId","0x2324"` arguments to the ganache entry point command. But typically the chainId of ganache is 1337, and in fact, many of our unit tests in other repos rely on this convention. They throw errors like the following:

```
ValueError: Unsupported chain id: 8996
```

This issue is to change the `chainId` to `1337`

**Comment by alexcos20** [comment]
Always, our chainId was 8996 (0x2324).  The recent commit just fixes that
