### ISSUE TITLE
V4 - Change ports of some components

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#272]
These ports are most of the time already in use on developer's machines:

- `3000` (used by Create React App, Next.js, lots of other js frameworks)
- `5000` (used by macOS Monterey by default as AirPlay receiver)
- `8000` (used by Gatsby.js, and our market)

Please change these ports to something else so especially frontend devs do not have to change local ports of their frontend apps just for barge. Using ubiquitous ports from widely used development tools should be avoided in the future too.

Needs a decision if we only want to change the exposed ports here in `barge`, or if we change the default ports in each respective component.

**Comment by maldo-ctrl** [comment]
I have checked our current port usage against the following sources, looking for conflicts

1. https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
2. search among known products and frameworks 

The following is the result of the research with proposed alternatives in cases of conflict:

| Component name      | Required by        | Version                           | IP Address      | Ports exposed |  Conflicts |  Alternative |
| --------------      | ------------------ | --------------------------------- | --------------- | ------------- |  ------------- |  ------------- |
| ganache             |  ocean-contracts   | latest                            | 172.15.0.3      | 8545 -> 8545  |✔️|
| ocean-contracts     |                    | v0.6.7                            | 172.15.0.14     |               |✔️|
| Aquarius            |                    | v3.1.1                           | 172.15.0.5      | ~~5000~~ -> 5000  |❌ 5000 commplex-main | 5110|
| Elasticsearch       |  Aquarius          | 6.8.3                             | 172.15.0.6      |               |✔️|
| Provider            |                    | v0.4.16                            | 172.15.0.4      | 8030 -> 8030  |✔️|
| Provider2           |                    | v0.4.16                            | 172.15.0.7      | 8030 -> 8030  |✔️|
| RBAC Server         |                    | main                              | 172.15.0.8      | ~~3000~~ -> 3000  |❌ 3000 react| 3301|
| GraphNode           |                    | oceanprotocol/graph-node:latest   | 172.15.0.15     | ~~9000~~ -> 8000 ,~~9001~~ -> 8001 , ~~9020~~ -> 8020,  9030 -> 8030, 9040 -> 8040  |❌ 9000 sentry, ❌ 9001 ETLServiceMgr, ❌ 9020 tambora |9003,9004,9012 |
| Graphipfs           |                    | ipfs/go-ipfs:v0.4.23              | 172.15.0.16     | ~~5001~~ -> 5001  |❌ 5001 commplex-link |  5040 | 
| Graphpgsql          |                    | postgres                          | 172.15.0.7      | 5432 -> 5432  |✔️|
| Dashboard           |                    | portainer/portainer               | 172.15.0.25     | ~~9100~~ -> 9000  | ❌ 9100 hp-pdl-datastr | 9110|
| Redis           |                    | bitnami/redis:latest               | 172.15.0.18     | 6379 -> 6379  |✔️|

**Comment by mihaisc** [comment]
Looks good.

**Comment by DMats** [comment]
> Needs a decision if we only want to change the exposed ports here in barge, or if we change the default ports in each respective component.

Based on the changes in #276 It appears we are only changing the exposed ports in barge.

**Comment by AnaLoznianu** [comment]
Marking this as blocked as we need to coordinate the port number change on all our components. Till we have everything in review and ready to merge, we cannot merge this one

**Comment by AnaLoznianu** [comment]
Closing this as is not needed anymore
