### ISSUE TITLE
Update ganache-cli to EIP-1559-compatible hardfork

### ISSUE THREAD

**Issue by MantisClone** [oceanprotocol/barge#277]
Testing performed in the provider repo shows that EIP-1559 transactions submitted to ganache running in barge, fail with the following error:

```
"Method eth_maxPriorityFeePerGas not supported."
```

Currently, ganache is started with `--hardfork istanbul` option:

```
entrypoint: ["node", "/app/ganache-core.docker.cli.js", "--db", "./ganache_cache","--chainId","0x2324","--networkId","0x2324","--gasLimit","10000000000","--gasPrice","1","---hardfork","istanbul","--mnemonic","${GANACHE_MNEMONIC}"]
```

I believe upgrading to `london` or `arrowGlacier` will allow EIP-1559 transactions.

EDIT: 
We're already using the latest image from https://hub.docker.com/r/trufflesuite/ganache-cli/. It hasn't been updated in over a year so the latest supported hard fork is `muirGlacier`. Upgrading to support EIP-1559 transactions will likely involve changing docker image for ganache and is not as simple as I anticipated.

**Comment by DMats** [comment]
Hmm... `london` isn't supported either.

```
ganache_1          | Error: Hardfork with name london not supported
```

Maybe I need to upgrade `ganache-core` version first.

```
ganache_1          | Ganache CLI v6.12.2 (ganache-core: 2.13.2)
```

**Comment by DMats** [comment]
We're already using the latest image from https://hub.docker.com/r/trufflesuite/ganache-cli/. It hasn't been updated in over a year so the latest supported hard fork is `muirGlacier`. Upgrading this is not as simple as I anticipated.

**Comment by DMats** [comment]
We decided to delay upgrading to EIP-1559 transactions.

**Comment by trentmc** [comment]
#339 (done) gets latest Ganache
