### ISSUE TITLE
Aquarius fails to process MetadataCreated event when creating dataset using Barge

### ISSUE THREAD

**Issue by rogargon** [oceanprotocol/barge#302]
**Describe the bug**

Trying to use a market on top of a locally deployed Barge. Capable of going through the process of publishing a new dataset. Everything seems to work a success is reported after signing the final 3 transactions. However, the just published cannot be found.

Looking at Aquarius output, the creation event is captures but it seems to be an error when calling decrypt on the provider:

> aquarius.events.events_monitor - ERROR - Error processing MetadataCreated event: HTTPConnectionPool(host='0.0.0.0', port=8030): Max retries exceeded with url: /api/services/decrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f715cd0da60>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> event=AttributeDict({'logIndex': 0, 'transactionIndex': 0, 'transactionHash': HexBytes('0xe90b972eb6d68b552b988b2aed94485cbf2803b7e17e58bb5f752089dabd775e'), 'blockHash': HexBytes('0xd36cd..., 'type': 'mined', 'removed': False})

**To Reproduce**
1. Start Barge locally
2. Copy local contracts to Market
3. Start market
4. Go through new dataset publishing process, which finishes successfully on the user interface after completing the 3 required transactions with MetaMask
5. The new dataset cannot be found, even after some minutes, the start_barge.sh command output shows the error detailed above, it seems Aquarius failed to process the creation event.

**Expected behavior**
The just created dataset appears in the market's user interface.

**Additional context**
Using the last version of Barge, with Aquarius v4.1.0.

**Comment by mihaisc** [comment]
can you try using http://{your local ip}:8030 to access the provider. You should be able to access this from the market and Aquarius should resolve this ip as well.

**Comment by rogargon** [comment]
Thanks, @mihaisc, it worked now. I have been able to publish a dataset and then browse it because it has been properly indexed by Aquarius. Closing this issue. 

I have made some changes to the market code to be able to work with Barge's infrastructure. For instance adding the Barge network to the list of market networks. I'll share the changes once I make sure all is working as expected.
