### ISSUE TITLE
Purge flag not working due to missing variable

### ISSUE THREAD

**Issue by htcarr3** [oceanprotocol/barge#312]
**Describe the bug**
start_ocean.sh script does not properly purge. 
See line 263 with `eval docker-compose --project-name=$PROJECT_NAME "$COMPOSE_FILES" -f "${NODE_COMPOSE_FILE}" down`
NODE_COMPOSE_FILE is not defined anywhere, which yields null after -f, which breaks that command

**To Reproduce**
Try to run the script with all options, then stop and rerun with --purge

**Expected behavior**
I would expect this flag to remove all containers running in the project

**Screenshots**
![image](https://user-images.githubusercontent.com/9591402/184981266-545101b1-f0cb-4d06-ad06-3a74e8e9e3bd.png)
![image](https://user-images.githubusercontent.com/9591402/184981130-1008b7c3-a92f-4480-aa08-2819ca4feae3.png)

**Desktop (please complete the following information):**
 - OS: Windows (but using docker dev environment, so this is running inside a linux vm)
 - Browser Edge

**Comment by htcarr3** [comment]
Not sure where NODE_COMPOSE_FILE is, or where it is expected to come from, but assuming it is extraneous, then this change solves the issue:
`eval docker-compose --project-name=$PROJECT_NAME $COMPOSE_FILES down`

Happy to submit a pr on this

**Comment by htcarr3** [comment]
also worth noting that lines 265 and 266 seem unnecessary as well, not sure where those would be defined based on anything else in this file
265: `docker network rm ${PROJECT_NAME}_default || true`
266: `docker network rm ${PROJECT_NAME}_backend || true`

**Comment by AnaLoznianu** [comment]
Thanks for opening this issue :) It would be great if you can open a PR for this issue

**Comment by htcarr3** [comment]
Happy to, I will try to get my local fixes pushed to a fork in the next day or so

**Comment by htcarr3** [comment]
@AnaLoznianu, open pr on this: https://github.com/oceanprotocol/barge/pull/327
