### ISSUE TITLE
Aquarius spams the barge logs, hurting ability to debug or know what's going on

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/barge#314]
If I start Barge in a standard flow, e.g. for c2d like: './start_ocean.sh --with-c2d`

Then I get hundreds or thousands of lines like the following. Sometimes >50 within a single second. 
```
aquarius_1         | 2022-09-07 14:41:03,257 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:5b2a975c65510320b18a0b49fc8a4d4d76f64dfdce6a85d013c55df8266eb568
aquarius_1         | 2022-09-07 14:41:03,260 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:5b2a975c65510320b18a0b49fc8a4d4d76f64dfdce6a85d013c55df8266eb568
aquarius_1         | 2022-09-07 14:41:03,262 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:5b2a975c65510320b18a0b49fc8a4d4d76f64dfdce6a85d013c55df8266eb568
aquarius_1         | 2022-09-07 14:41:03,265 - aquarius.app.es_instance - DEBUG - elasticsearch::read::did:op:5b2a975c65510320b18a0b49fc8a4d4d76f64dfdce6a85d013c55df8266eb568
```

Options to fix:
1. change start_ocean.sh from DEBUG to a higher level INFO; or 
2. (probably better) in aquarius itself, change these DEBUG logs to a lower level (DEBUG2? does it exist?) and ensure that ocean.sh keeps using DEBUG level; or
3. something else?

**Comment by AnaLoznianu** [comment]
Do it for aquarius and subgraph as well

**Comment by htcarr3** [comment]
I will second that Aquarius events monitor is likely the major contributor to the log-insanity. What might be nice as well is to provide a barge flag that just adds the --detached or -d flag to the docker compose statement, then it all runs in the background without any logging on STDOUT
