### ISSUE TITLE
start_ocean.sh --with-c2d doesn't boot properly, causing downstream fails in C2D README etc

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/barge#315]
**Describe the bug**
I'm going through the ocean.py [C2D README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md). 

It all goes fine until this line:
```python
free_c2d_env = ocean.compute.get_free_c2d_environment(compute_service.service_endpoint)
```

Giving the traceback:
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/ocean/ocean_compute.py", line 165, in get_free_c2d_environment
    return next(env for env in environments if float(env["priceMin"]) == float(0))
  File "/home/trentmc/code/play/venv/lib/python3.10/site-packages/ocean_lib/ocean/ocean_compute.py", line 165, in <genexpr>
    return next(env for env in environments if float(env["priceMin"]) == float(0))
TypeError: string indices must be integers
```

This issue was originally in ocean.py. 

**But as we dug further, it's clear that the issue is not ocean.py but barge: `start_ocean.sh ---with-c2d` isn't outputting any artifacts we expect in `~/.ocean/ocean-c2d` and it should be.**

 And, the issue seen with `get_free_c2d_environment()` is simply a downstream artifact that things aren't working.

Note: [I'd created a PR for this issue in ocean.py](https://github.com/oceanprotocol/ocean.py/pull/907) up-front so that we can leverage the CI. The PR doesn't encounter these issues. So, it's something local. (And I've now closed the PR.)

**Comment by trentmc** [comment]
Here's another run log. I started fresher this time. Let's see if it can work.

1. purged old docker repos

2. opened a new bash terminal. 

3. ran `start-ocean.sh --with-c2d >out.txt 2>&1` which dumps stdout and stderr to out.txt.

4. Then waited. Notes from observing the log...

- Log file attached. 
- I saw that error yesterday, reported in [this ocean.py issue](https://github.com/oceanprotocol/ocean.py/issues/904). I tried many fixes. In the end what worked was rebooting the computer itself - with the theory that docker processes were tripping over each other. But note that it seems to recover (see below)

Error summary:
```text
kindcluster_1      | Server:
kindcluster_1      | ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
kindcluster_1      | 2022-09-07 15:42:21,924 INFO spawned: 'dockerd' with pid 118
kindcluster_1      | Error on line 29
kindcluster_1      | Startup timeout, didn't become healthy after 3 mins.. details:
```

However it tried again later and succeeded:
```
mkindcluster_1      | 2022-09-07 15:42:22,972 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

(WILL ADD MORE HERE AS IT GOES)

**Comment by trentmc** [comment]
Next thing to try: like above, but with a reboot.

**Comment by trentmc** [comment]
Next thing I tried:

Like above, but with a step 0.5: 'sudo rm /var/run/docker.pid`. 
- I was inspired by [this](https://github.com/sameersbn/docker-gitlab/issues/1861#issuecomment-479916822), where they had a similar issue. It was also a tactic I saw while solving [ocean.py#904](https://github.com/oceanprotocol/ocean.py/issues/904).

WIP..

**Comment by trentmc** [comment]
Next thing I tried:

Combine all of the above, and run main command in sudo. That is:

0.5: `sudo rm /var/run/docker.pid`

1.0 pruned old docker repos: `docker system prune -a --volumes`

1.5 reboot computer

2. open a new bash terminal, cd to barge directory

3. ran `sudo ./start_ocean.sh --with-c2d >out.txt 2>&1` which dumps stdout and stderr to out.txt.

4. Then waited. Notes from observing the log...

WIP

**Comment by alexcos20** [comment]
running docker in docker in very complex..
running docker in k8 cluster, in docker, in docker is .. overkill...
You should have at least 8Gb of RAM free, and indeed, from time to time, linux cannot handle that and needs a reboot.

But the main thing is not barge.. it's ocean.py and provider.
If C2D engine does not start, provider should handle that.. and ocean.py should handle a proper response from provider.
But we are always assuming that we will get a perfect formatted JSON with all the available envs. Which, in reality, we may not...  Maybe AWS is down, maybe on-premise 1000 cpu cluster is down..

**Comment by trentmc** [comment]
C2D README should work out-of-the-box, of course. As it did before. If we need to make changes to it, or to barge, or to provider let's make changes.
