### ISSUE TITLE
Add env_var to mute graph-node logging. Update ./start_ocean.sh via barge to mute grap-node logs.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/barge#321]
### Problem:
Right now, subgraph defaults to graph-node having logger turned on.
https://github.com/oceanprotocol/ocean-subgraph/blob/9fb268cde9e1dabf54fde1f95bc39a04d157e776/docker/docker-compose.yml#L21

I have expanded my own cli history to handle this, however for anyone else, this creates tens of thousands of lines of debug to get spat out, which means you need to figure out other ways to verify contract deployments, or grab ganache pk's.

Can we disable this by default, or put it into an env_var so we can run barge with this muted?

### DOD:
- [ ] Attach `graph-node` log settings into an {env_var}.
- [ ] Attach it to barge via ./start_ocean.sh

**Comment by trentmc** [comment]
@idiom-bytes it adds complexity to support a logging feature for each different docker process.

Fortunately, there's a better way, that's already supported: run `docker logs` from a separate console to see logs for a specific process. 

Here's how.

```console
# see docker processes. Incl NAMES (far right), CONTAINER_ID (far left)
docker ps -a

# view logs of NAME = ocean_ocean-contracts_1
docker logs ocean_ocean-contracts_1

# view logs of CONTAINER_ID = 661209b66c75
docker logs 661209b66c75
```

Further info: [Docs on docker CLI](https://docs.docker.com/engine/reference/commandline)

I believe this will solve your challenge @idiom-bytes. Therefore, closing this issue. Feel free to re-open if you see that I missed something.
