### ISSUE TITLE
Aquarius does not start on macOS Monterey port 5000 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/barge#343]
From Veronica: 

"Aquarius does not start on macOS Monterey port 5000 due to AirPlay receiver issue. Must turn AirPlay receiver off in System Preferences > Sharing
https://nono.ma/port-5000-used-by-control-center-in-macos-controlce Refer to this issue brought up by Alex: "

**Comment by AnaLoznianu** [comment]
As discussed today in the planning: This is a high-priority issue but too risky to do it now. We will fix it next year. 
For now, we will add a comment in the barge read.me to disable the airplay receiver till we deploy a proper fix

**Comment by Abrom8** [comment]
@AnaLoznianu Any updates on this issue?

**Comment by AnaLoznianu** [comment]
@Abrom8 I know the team has a workaround for this problem - change in barge the port for aquarius. At this moment the full solution is not implemented yet. Does it block you?

**Comment by Abrom8** [comment]
I'm using the AirPlay Receiver workaround for now, but it'd significantly enhance the user experience if the root issue was addressed. This could potentially encourage more people to use this tool, improving overall project adoption.

**Comment by trentmc** [comment]
We've found Barge outside Linux to be highly problematic. So now we recommend just to use Linux. For Windows and MacOS, we recommend using a VM.

See this commit https://github.com/oceanprotocol/barge/commit/28faf32b356fbd8663e10d8a2698233d3e285d5c.

Therefore this issue is wontfix.
