### ISSUE TITLE
Barge on different OS

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/barge#349]
So far, Barge was designed as Linux tool, not guaranteeing any compatibility with other OS.

But we see more and more users using Windows or MacOs, which creates either friction, or does not work at all

Proposal:
 - make sure barge works with multiple OS

How to:
 - detect OS
 - based on that, make necessary changes (ie:  on MacOs, there is no 172.15.. network.   so aqua must connect to 127.0.0.1:8545 for RPC)
 - export all URLs into a file ($HOME/.ocean/urls.json), so ocean.js/py can use them properly, without additional logic needed.  File structure:
 ```json
{
 "aquarius": "http://127.0.0.1:5000",
 "provider": "http://127.0.0.1:8300",
...
}
```

**Comment by trentmc** [comment]
We've found Barge outside Linux to be highly problematic. So now we recommend just to use Linux. For Windows and MacOS, we recommend using a VM.

See this commit https://github.com/oceanprotocol/barge/commit/28faf32b356fbd8663e10d8a2698233d3e285d5c.

Therefore this issue is wontfix.
