### ISSUE TITLE
Update the README to reflect correctly the supported os

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/barge#350]
We currently have misleading information in the main readme about the supported oses.

- [ ] Barge is not working on windows.
- [ ] Barge runs minimally on a macOS(C2D is not supported). 

Update the readme to reflect correctly the supported OSes

**Comment by trentmc** [comment]
This was done on Oct 6, 2023 in commit https://github.com/oceanprotocol/barge/commit/28faf32b356fbd8663e10d8a2698233d3e285d5c
