### ISSUE TITLE
No SUBGRAPH_URLS env variable defined for Aquarius

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/barge#370]
**Describe the bug**
Aquarius it's looking for `SUBGRAPH_URLS` to identify subgraph url. Right now there is nothing defined and Aquarius fails to do any interaction with the Subgraph

**Comment by trentmc** [comment]
Is this done? The issue is a few months old. cc @KatunaNorbert

**Comment by trentmc** [comment]
Since no response: closing.
