### ISSUE TITLE
Error during vesting wallet deployment

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/barge#395]
ocean-contracts-1  | Deploying VestingWallet0
ganache-1          | eth_getBlockByNumber
ocean-contracts-1  | Error: value out-of-bounds (argument="durationSeconds", value=-133390, code=INVALID_ARGUMENT, version=abi/5.7.0)

**Comment by alexcos20** [comment]
fixed in https://github.com/oceanprotocol/contracts/pull/862
