### ISSUE TITLE
Error connectiong from brizo to Aquarius (bad hostname)

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/barge#60]
# Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository.

## Current Behavior

When I send the initialize HTTP request to brizo it gets a HTTP 500 error. Internally in the logs I can see:
```
brizo_1                    | 2018-11-26 08:35:31 8ef06e4c03fa root[58] INFO got "consume" request: {'did': 'did:op:5dc588cb2cfd4c6fa204978ca314b08a47b86753bc004e38857d96ab6d30b296', 'serviceAgreementId': '22f7582f3ae64d75b586217bd3b6a994c887d24d3bd14ffe96642f18387db6bd', 'serviceDefinitionId': '1', 'signature': 'b964193633ff753522f283c6edcc863f53b618d2dba27e5d284438e28ab90b5d', 'consumerAddress': '0x068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0'}
brizo_1                    | 2018-11-26 08:35:31 8ef06e4c03fa root[58] ERROR HTTPConnectionPool(host='0.0.0.0', port=5000): Max retries exceeded with url: /api/v1/aquarius/assets/ddo/did:op:5dc588cb2cfd4c6fa204978ca314b08a47b86753bc004e38857d96ab6d30b296 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0541a808d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

Looks Brizo is sending a request to resolve a DID to http://0.0.0.0:5000 but the brizo Docker image can't resolve this address.
Internally Brizo can resolve this address: http://aquarius:5000

**Comment by jernejpregelj** [comment]
Reopening this for having same problem on Mac:

Terminal log from Barge:
![screenshot 2019-02-15 at 16 18 56](https://user-images.githubusercontent.com/7147341/52865717-883d5e00-313d-11e9-85ef-c5648e8c2dd2.png)

Console.log in browser sending the request:
![screenshot 2019-02-15 at 16 19 24](https://user-images.githubusercontent.com/7147341/52865719-883d5e00-313d-11e9-8a12-a96af2f492f7.png)

Running Barge with: ./start_ocean.sh --no-pleuston --local-spree-node --latest --no-acl-contract

Versions to replicate this bug:
AQUARIUS_VERSION=v0.1.8
BRIZO_VERSION=v0.2.0
KEEPER_VERSION=v0.6.12

Versions that are bug free:
AQUARIUS_VERSION=v0.1.5
BRIZO_VERSION=v0.1.7
KEEPER_VERSION=v0.5.3

**Comment by jernejpregelj** [comment]
Solution:
Aquarius url is save when generating asset. In case of using MacOSX it is possible to use "docker.for.mac.localhost" to access Aquarius in docker from Browser
