### ISSUE TITLE
Docker-compose looks for environment variable NETWORK_NAME, not KEEPER_NETWORK_NAME

### ISSUE THREAD

**Issue by theoturner** [oceanprotocol/barge#64]
See https://github.com/oceanprotocol/keeper-contracts/blob/develop/scripts/keeper.sh#L5

**Comment by H34D** [comment]
@theoturner please retry with the latest version from `develop` branch. `./start_ocean.sh --latest --local-kovan-node` to connect all components to `kovan` or `--local-nile-node` to connect all components to the ocean `nile` testnet.

**Comment by H34D** [comment]
@theoturner should be working with current version of `barge`
