### ISSUE TITLE
Remove AQUARIUS_URL from brizo.env

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/barge#82]
Following on from https://github.com/oceanprotocol/brizo/issues/43 (now resolved):

Brizo doesn't need `AQUARIUS_URL` so setting it in `brizo.env` is not necessary.

https://github.com/oceanprotocol/docker-images/blob/8b24ab4748cef27ce2dd0694769476ee207eb850/brizo.env#L7

Suggestion: Remove `AQUARIUS_URL` from `brizo.env`. That shouldn't break anything because the only file using `brizo.env` (or `BRIZO_ENV_FILE`) is `compose-files/brizo.yml` and Brizo doesn't need `AQUARIUS_URL` any more.

(If something else needs `AQUARIUS_URL` then it should get set by something other than `brizo.env`.)

**Comment by jcortejoso** [comment]
Fixed in #90.
