### ISSUE TITLE
start_oceah.sh fails on Fedora 29

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/barge#94]
## Expected Behavior

start_ocean.sh should start successfully

## Current Behavior

Start fails with:
**Could not connect to your Ethereum client. Please check that your Ethereum client**

Complete log attached below.

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Look on https://alt.fedoraproject.org/cloud/ to find the most recent supported AWS AMI for Fedora 29 is: Fedora-Cloud-Base-29-1.2.x86_64-hvm-us-east-1-gp2-0 - ami-0ca275747dcc62c18
2. Press the "click to launch" button to launch this AMI as an EC2 instance
3. In the AWS console ensure that the instance size is at least **t2.large** (2 vCPU 8 GB RAM) and that a keypair is set
4. Log into the fedora instance
5. Add required packages: dnf update && dnf search git && dnf search docker-compose
6. Get barge
```
mkdir -p src/github/oceanprotocol
git clone https://github.com/oceanprotocol/barge.git
cd barge
```
7. Start ocean:
```
script -c './start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node --purge' start-ocean.log
```

### Possible Solution

???

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: commit f7e21e503de52dd94e2715b2952943ef56613f35 (HEAD -> develop, origin/develop, origin/HEAD)
* OS: fedora 29

Do these even matter on the host system?
* Python: 3.7.2
* Solidity: x.x.x
* JavaScript: x.x.x
* Node: x.x.x

## Failure Logs

[fedora-start-ocean.log](https://github.com/oceanprotocol/barge/files/2738876/fedora-start-ocean.log)

**Comment by jcortejoso** [comment]
I tried to reproduce the issue but for me it is working in Fedora (ami `Fedora-Cloud-Base-29-1.2.x86_64-hvm-us-east-1-gp2-0`, and latest version of docker-ce stable `Docker version 18.09.1, build 4c52b90` and docker-compose `docker-compose version 1.23.2, build 1110ad01`).

I added my user (`fedora` for the ami) to `docker` group and run this command:
`KEEPER_VERSION=v0.5.3 bash -x ./start_ocean.sh --latest --no-brizo --no-pleuston --local-spree-node --purge`

Due a compatibility issue we need to set currently KEEPER_VERSION to the latest stable version (`v0.5.3`) but it does not seem it is related with the problem shown in your logs. It seems to have some problem mounting the files inside the docker containers, and also strange the `mongodb_1` container error. Can you run the script without the `script` command? Also have you configured your user inside `docker` group? If not you would need to run with `sudo`.
