### ISSUE TITLE
Brizo starts before keeper-contracts on multiple starts (linux)

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/barge#98]
## Expected Behavior

Brizo MUST wait until contracts are deployed. 

This relates to the local contracts (~/.ocean/) having root ownership.

## Current Behavior

Brizo sometimes will skip the wait defined in `docker-entry.sh`; 

```
  2 KEEPER_NETWORK_NAME="${KEEPER_NETWORK_NAME:-development}"
  3 export CONFIG_FILE=/brizo/config.ini
  4 envsubst < /brizo/config.ini.template > /brizo/config.ini
  5 if [ "${LOCAL_CONTRACTS}" = "true" ]; then
  6   echo "Waiting for contracts to be generated..."
  7   while [ ! -f "/usr/local/keeper-contracts/ready" ]; do
  8     sleep 2
  9   done
 10 fi
```

And then either fail, or worse, there will be multiple versions of the same contract, one in your local and one in Brizo? 

Ref. https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by jcortejoso** [comment]
Most of the work of the fix must be accomplished in `keeper-contracts` entrypoint. I will try to provide a fix soon. By now, a quick fix can be run `sudo rm -rf ~/.ocean/keeper-contracts/artifacts/ready` in your host before running `start-ocean.sh`.
